### ISSUE TITLE
[v2.0] Pending requests to join a group

### ISSUE THREAD

**Issue by jsamr** [Meteor-Community-Packages/meteor-roles#175]
Often, permissions are granted dynamically. For example, a member wants to join some group but needs the approval of a group responsible. 

**User case :**
Being a member of the project which id is "LAJ6xyDrsKt8MEqQ5" is equivalent to `Roles.userIsInRole(userid,'project.member',"projects.LAJ6xyDrsKt8MEqQ5")` returning `true`. 

As for now, if one needs a pending request system, he has to implement it.  

**API :**
But what about adding an optional field `pending` that, when set to `true`, allows the following mechanism : 
- Adding a user to a pending Role like following `Roles.addUsersToRoles(userid,'project.member','projects.LAJ6xyDrsKt8MEqQ5', {pending:true})` doesn't make it an effective member. 
- I.E `Roles.userIsInRole(userid,'project.member','projects.LAJ6xyDrsKt8MEqQ5')` still returns `false`
- However `Roles.userIsInRole(userid,'project.member',"projects.LAJ6xyDrsKt8MEqQ5",{pending:true})` returns `true`
- `Roles.getUsersInRole('project.member',{partition:'projects.LAJ6xyDrsKt8MEqQ5',pending:true})` returns pending users only. 
- `Roles.acceptUserRoles(userid,'project.member', 'projects.LAJ6xyDrsKt8MEqQ5')` will set `pending` to `false`. **Works only if roles are already assigned to user.**

What do you think about it? Could it be a candidate for an extension ?

**Comment by mitar** [comment]
Yes, this sounds pretty good. The schema was designed so that it would be easy to add extra fields to the subdocuments without breaking backwards compatibility.

I would prefer if this would be an extension though. If you are interested in this, could you try to implement it and report back if there are any features missing in core for you to be able to do it? I am thinking that we might have to split permission checks into two functions: one which prepares the query, and another which then runs it and returns true or false. In this way one can wrap the first function easily to add more conditions to the query.

**Comment by sveinburne** [comment]
Great. I will try it during this month, as it would perfectly fit my app needs, and will keep you informed.
I'm obviously less experienced (didn't even know I could squash comments), but I'll do my best :)

**Comment by Billybobbonnet** [comment]
I had a similar feature in my project, except I used my own user right management system. I consider switching to alanning:roles but I didn't plan to move the invitations and membership requests into it. Have you made some progress? Maybe I could help.

Just as ideas, here are a couple of features I implemented:
- Invitations using a user email (from a group admin)
- Membership requests
- Recently left (i.e. can rejoin the group without another membership request within 24hrs)

**Comment by jedwards1211** [comment]
In my opinion, for the sake of simplicity and security, `roles` should only contain the roles that the user currently has.  If this package forgot to check the `pending` field in just one place, it would open a security hole.

There is one potential exception I can think of though: role expiration dates.  Many organizations want to grant users permissions for a limited period of time, and having this package check an `expirationDate` field in `userIsInRoles` could be a bit more robust than having some extension remove roles on their expiration date, since that extension might go down at some point.

The other thing about role requests is that multiple requests for the same user/role could be made before any is granted, so you'd really want to have a separate collection of role requests.  Organizations might want to keep track of all kinds of metadata about the request as well, for instance:
```js
{
  // id of user who is making the request
  from: string,
  // id(s) of user(s) who are asked to approve the request
  to: string | string[],
  // id of user whom roles are being requested for
  targetUser: string,
  // requested role(s)
  roles: string | string[],
  // date request was made
  createdDate?: Date,
  // requesting for user to have role(s) until this date
  expirationDate?: Date,
  // explanation of why role(s) are being requested
  comment?: string
}
```
Storing information like this in the Users collection, as opposed to a separate collection, would:
* not be as convenient to query or index efficiently
* trigger unnecessary reactive updates

**Comment by mitar** [comment]
Closing this in favor of a third party extension. I think there are multiple ways how to do this, so it is hard to make one which would everyone like.
