### ISSUE TITLE
How to get users in a group?

### ISSUE THREAD

**Issue by luixal** [Meteor-Community-Packages/meteor-roles#217]
The only option I see right now is going through all users and check their groups. Seems quite heavy.

Any ideas?

**Comment by wiserweb** [comment]
One solution might be to build your own query.

Try this in Robomongo

`
db.getCollection('users').find({ 'roles.__global_roles__': {$ne:null}})
`
You should get back all the users that have any group name.

Now just change for the group you are looking for 

`
db.getCollection('users').find({ 'roles.__global_roles__':  {$in: ['groupname']} })
`

Hope this helps.

**Comment by muninn9** [comment]
I have a similar problem where I need to return all users with a specified role from all groups.

`db.getCollection('users').find({ 'roles.__global_roles__': {$ne:null}})` just returns all users with a group name called "\_\_global_roles\_\_".

It would be nice if Roles.getUsersInRole("specifiedRole") just returns all users with the "specifiedRole" in all groups when no group is specified.

**Comment by alanning** [comment]
Yeah, this is a known pain-point but the good news is that Roles v2 let's you do this kind of thing.  So try v2!  You can find it on the [v2 branch](https://github.com/alanning/meteor-roles/tree/v2.0) in the repo.  You'll need to clone the repo to your app's `packages` directory to get the functionality since at this time its not up on Atmosphere yet.

See the v2 readme for migration and changes between v1 and v2.  Should be pretty much drop-in (but be sure to run the migration script).

FYI, the db structure of v1 `roles` field on the user record didn't allow for indexing so this kind of operation would be terrible to do performance-wise.  But the v2 structure allows indexes on these.

**Comment by kan-ashwin** [comment]
Is there a plan to release v2 ?
How do we fetch users in a role with v2 ?

**Comment by mitar** [comment]
Released.
