### ISSUE TITLE
MongoError: Cannot apply $pull to a non-array value

### ISSUE THREAD

**Issue by rich-m21** [Meteor-Community-Packages/meteor-roles#282]
I'm trying to remove users in roles using **removeUsersFromRoles** but get the mongo error on title
Meteor version 1.8.1
alanning:roles@1.2.16
```
            const currentRoles = Roles.getRolesForUser(data.userId);
            console.log(currentRoles);
            console.log(Array.isArray(currentRoles));
            console.log('==============Removing Past Roles==============');
            Roles.removeUsersFromRoles(data.userId, currentRoles);
```
currentRoles prints out
```
I20190911-23:49:34.788(-6)? [ 'app-ratings',
I20190911-23:49:34.794(-6)?   'visibility',
I20190911-23:49:34.800(-6)?   'manifest',
I20190911-23:49:34.802(-6)?   'statistics',
I20190911-23:49:34.812(-6)?   'healthcheck',
I20190911-23:49:34.814(-6)?   'live-poi',
I20190911-23:49:34.821(-6)?   'app-logs',
I20190911-23:49:34.822(-6)?   'super-admin',
I20190911-23:49:34.826(-6)?   'users-admin' ]
```
and isArray prints out **true**
Help!

**Comment by alanning** [comment]
I think the function documentation is misleading.  Since that user record uses "groups", you need to also pass the target group to `Roles.removeUsersFromRoles(data.userId, currentRoles, 'qa')`.

Not passing a group _could_ indicate you want to remove the user from those roles in any group but that's not the way the code works today since it still supports library users who don't use groups at all:
https://github.com/alanning/meteor-roles/blob/master/roles/roles_common.js#L227-L232

**Comment by mitar** [comment]
I think I just published a package where you should get a better error message in this case.
