### ISSUE TITLE
Default Role of created user

### ISSUE THREAD

**Issue by SantoshSrinivas79** [Meteor-Community-Packages/meteor-roles#35]
Is there a way to create a default user role ... say "default"

As the docs say, this cannot be included in the `Accounts.onCreateUser` function as the user has not been created yet.

**Comment by AdamBrodzinski** [comment]
Thanks @carlodicelico this helps a lot!

**Comment by danielflippance** [comment]
@alanning Looking at the code for Accounts.createUser, it doesn't seem to return the user id and the callback only returns an err. 

https://github.com/meteor/meteor/blob/master/packages/accounts-password/password_client.js#L113

Is this the code you're referring to? Maybe it has changed since April 2014? If so, any idea where to get the id from now?

**Comment by danielflippance** [comment]
@alanning Aha, per the docs: 

"On the client, this function logs in as the newly created user on successful completion. On the server, it returns the newly created user id."

**Comment by logvik** [comment]
You can use the package **matb33:collection-hooks**

```
Meteor.users.after.insert(function (userId, doc) {
  Roles.addUsersToRoles(doc._id, ['role'], Roles.GLOBAL_GROUP);
});
```

**Comment by stefanilie** [comment]
@logvik Thanks man, that worked for me! 
Just a minor question here: if I have a meteor method, in which i run this so that i can add roles based on client-side decisions, does this scale? I mean, if I have X user creations per second, this hook will know what doc._id has what role?

```javascript
Meteor.methods({
'addRole': function(role){
    Meteor.users.after.insert(function(userId, doc){
      Roles.addUsersToRoles(doc._id, role);
    })
  }
});
